Watching for file changes with StatReloader
2025-01-29 20:57:39,446 django.utils.autoreload INFO     Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/nix/store/lwl8ysfi2hhcyki6pc9qqbybzm5z55wv-python3-3.9.21/lib/python3.9/threading.py", line 980, in _bootstrap_inner
    self.run()
  File "/nix/store/lwl8ysfi2hhcyki6pc9qqbybzm5z55wv-python3-3.9.21/lib/python3.9/threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "/home/runner/workspace/.pythonlibs/lib/python3.9/site-packages/django/apps/config.py", line 193, in create
    import_module(entry)
  File "/nix/store/lwl8ysfi2hhcyki6pc9qqbybzm5z55wv-python3-3.9.21/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'search'